spring:
  autoconfigure:
    exclude:
      - com.alibaba.cloud.nacos.NacosConfigAutoConfiguration
      - com.alibaba.cloud.nacos.NacosDiscoveryClientAutoConfiguration
      - com.alibaba.cloud.nacos.discovery.NacosDiscoveryAutoConfiguration
      - com.alibaba.cloud.nacos.discovery.NacosDiscoveryClientAutoConfiguration
      - com.alibaba.cloud.nacos.NacosServiceAutoConfiguration
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: talkai-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: talkai-user
          uri: http://localhost:8084
          predicates:
            - Path=/api/user/**
        - id: talkai-chat
          uri: http://localhost:8082
          predicates:
            - Path=/api/chat/**
        - id: talkai-model
          uri: http://localhost:8083
          predicates:
            - Path=/api/model/**
        - id: talkai-agent
          uri: http://localhost:8086
          predicates:
            - Path=/api/agent/**
        - id: talkai-search
          uri: http://localhost:8087
          predicates:
            - Path=/api/search/**
        - id: talkai-photo
          uri: http://localhost:8089
          predicates:
            - Path=/api/photo/**

# Gateway需要排除 Nacos 服务发现相关的自动配置, 否则启动失败
